import Head from 'next/head'
import Image from 'next/image'
import LoginPage from '@/components/LoginPage'
import { useAuth } from '@/context/AuthContext'
import UserDashboard from '@/components/UserDashboard'

export default function Home() {

  const { currentUser } = useAuth()
  console.log("currentUser", currentUser)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {!currentUser && <LoginPage />}
        {currentUser && <UserDashboard />}
      </>
    </>
  )
}
